version: '3.8'

services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: docker-test
      POSTGRES_USER: docker-tester
      POSTGRES_PASSWORD: docker-tester-password
    volumes:
      - db-data:/var/lib/postgresql/18/main
    ports:
      - "5432:5432"

volumes:
  db-data:
